### ISSUE TITLE
Erro ao utilizar o dataset-serialize-adapter utilizando o lazarus 2.2.6

### ISSUE THREAD

**Issue by elvisbayerl** [viniciussanchez/dataset-serialize-adapter-restrequest4delphi#1]
Ao utilizar a rotina abaixo, esta apresentado um erro na unit "DataSet.Serialize.Adapter.RESTRequest4D", relacionado nas diretivas de compilação para o lazarus. 
  TRequest.New
    .BaseUrl('http://localhost:9000')
    .Resource('books')
    .AddParam('filter', AFilter)
    .Adapters(TDataSetSerializeAdapter.New(mtBooks))
    .Get;

O erro esta nas seguintas linhas:

linha 5
de
uses RESTRequest4D.Request.Adapter.Contract{$IFNDEF FPC}, DB{$ENDIF}, DataSet.Serialize;
para
uses RESTRequest4D.Request.Adapter.Contract{$IF DEFINED(FPC)}, DB{$ENDIF}, DataSet.Serialize;

linhas 54 e 56
de
  ActiveCachedUpdates(FDataSet, False);
  FDataSet.LoadFromJSON(aContent);
  ActiveCachedUpdates(FDataSet, True);
para
  {$IFNDEF FPC}
  ActiveCachedUpdates(FDataSet, False);
  {$ENDIF}
  FDataSet.LoadFromJSON(aContent);
  {$IFNDEF FPC}
  ActiveCachedUpdates(FDataSet, True);
  {$ENDIF}

**Comment by viniciussanchez** [comment]
Obrigado por reportar....

**Comment by elvisbayerl** [comment]
Talvez hoje eu consiga subir as alterações.

**Comment by edvilsonchaves** [comment]
Bom dia!
Estou tentando implementar isso na minha solução mas não estou conseguindo. 

Estou usando o Middleware Horse-Paginate.  Poderiam me ajudar?

```
        lRequest := TRequest.New;
        lRequest.BaseURL(TFuncoesStrings.StringConcatenada(DtmEntConfiguracoes.CampoPorNome('SERVIDOR_SYNCRO').AsString, DtmEntConfiguracoes.CampoPorNome('PORTA_SYNCRO').AsString, ':'));
        lRequest.BasicAuthentication(DtmEntConfiguracoes.CampoPorNome('USUARIO_SYNCRO').AsString, DtmEntConfiguracoes.CampoPorNome('SENHA_SYNCRO').AsString);
        lRequest.Resource(NomeEntidade);
        lRequest.DataSetAdapter(FdmEntidade);
        lRequest.Accept('application/json');

        AdicionarParametros(lRequest);

        lResponse := lRequest.Get;

```
