### ISSUE TITLE
F2613 Unit 'DataSet.Serialize.Adapter.RESTRequest4D' not found.

### ISSUE THREAD

**Issue by stonestecnologia** [viniciussanchez/dataset-serialize-adapter-restrequest4delphi#4]
![image](https://github.com/viniciussanchez/dataset-serialize-adapter-restrequest4delphi/assets/4261018/b93164b2-9770-477c-b5e5-6f89b425144c)

Seguindo a documentação, o delphi não localizou, a unit. 
Faltou alguma configuracao ?

**Comment by viniciussanchez** [comment]
Provavelmente você não instalou o https://github.com/viniciussanchez/dataset-serialize-adapter-restrequest4delphi
